/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionidRouteImport } from './routes/session/$sessionid'
import { Route as AuthServerRouteImport } from './routes/_auth/server'
import { Route as AuthClientOnlyRouteImport } from './routes/_auth/client-only'
import { Route as AppWorkflowRouteImport } from './routes/_app/workflow'
import { Route as AppVerificationsRouteImport } from './routes/_app/verifications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppQuestionnariesRouteImport } from './routes/_app/questionnaries'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomizationRouteImport } from './routes/_app/customization'
import { Route as AppBlocklistRouteImport } from './routes/_app/blocklist'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionidRoute = SessionSessionidRouteImport.update({
  id: '/session/$sessionid',
  path: '/session/$sessionid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthServerRoute = AuthServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientOnlyRoute = AuthClientOnlyRouteImport.update({
  id: '/client-only',
  path: '/client-only',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationsRoute = AppVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionnariesRoute = AppQuestionnariesRouteImport.update({
  id: '/questionnaries',
  path: '/questionnaries',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizationRoute = AppCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => AppRoute,
} as any)
const AppBlocklistRoute = AppBlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/analytics': typeof AppAnalyticsRoute
  '/blocklist': typeof AppBlocklistRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/questionnaries': typeof AppQuestionnariesRoute
  '/settings': typeof AppSettingsRoute
  '/verifications': typeof AppVerificationsRoute
  '/workflow': typeof AppWorkflowRoute
  '/client-only': typeof AuthClientOnlyRoute
  '/server': typeof AuthServerRoute
  '/session/$sessionid': typeof SessionSessionidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/analytics': typeof AppAnalyticsRoute
  '/blocklist': typeof AppBlocklistRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/questionnaries': typeof AppQuestionnariesRoute
  '/settings': typeof AppSettingsRoute
  '/verifications': typeof AppVerificationsRoute
  '/workflow': typeof AppWorkflowRoute
  '/client-only': typeof AuthClientOnlyRoute
  '/server': typeof AuthServerRoute
  '/session/$sessionid': typeof SessionSessionidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/blocklist': typeof AppBlocklistRoute
  '/_app/customization': typeof AppCustomizationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/questionnaries': typeof AppQuestionnariesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/verifications': typeof AppVerificationsRoute
  '/_app/workflow': typeof AppWorkflowRoute
  '/_auth/client-only': typeof AuthClientOnlyRoute
  '/_auth/server': typeof AuthServerRoute
  '/session/$sessionid': typeof SessionSessionidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/analytics'
    | '/blocklist'
    | '/customization'
    | '/dashboard'
    | '/documents'
    | '/questionnaries'
    | '/settings'
    | '/verifications'
    | '/workflow'
    | '/client-only'
    | '/server'
    | '/session/$sessionid'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/analytics'
    | '/blocklist'
    | '/customization'
    | '/dashboard'
    | '/documents'
    | '/questionnaries'
    | '/settings'
    | '/verifications'
    | '/workflow'
    | '/client-only'
    | '/server'
    | '/session/$sessionid'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/sign-in'
    | '/sign-up'
    | '/_app/analytics'
    | '/_app/blocklist'
    | '/_app/customization'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/questionnaries'
    | '/_app/settings'
    | '/_app/verifications'
    | '/_app/workflow'
    | '/_auth/client-only'
    | '/_auth/server'
    | '/session/$sessionid'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SessionSessionidRoute: typeof SessionSessionidRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionid': {
      id: '/session/$sessionid'
      path: '/session/$sessionid'
      fullPath: '/session/$sessionid'
      preLoaderRoute: typeof SessionSessionidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/server': {
      id: '/_auth/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthServerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/client-only': {
      id: '/_auth/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof AuthClientOnlyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workflow': {
      id: '/_app/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verifications': {
      id: '/_app/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof AppVerificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questionnaries': {
      id: '/_app/questionnaries'
      path: '/questionnaries'
      fullPath: '/questionnaries'
      preLoaderRoute: typeof AppQuestionnariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customization': {
      id: '/_app/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof AppCustomizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blocklist': {
      id: '/_app/blocklist'
      path: '/blocklist'
      fullPath: '/blocklist'
      preLoaderRoute: typeof AppBlocklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBlocklistRoute: typeof AppBlocklistRoute
  AppCustomizationRoute: typeof AppCustomizationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppQuestionnariesRoute: typeof AppQuestionnariesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerificationsRoute: typeof AppVerificationsRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBlocklistRoute: AppBlocklistRoute,
  AppCustomizationRoute: AppCustomizationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppQuestionnariesRoute: AppQuestionnariesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVerificationsRoute: AppVerificationsRoute,
  AppWorkflowRoute: AppWorkflowRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthClientOnlyRoute: typeof AuthClientOnlyRoute
  AuthServerRoute: typeof AuthServerRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientOnlyRoute: AuthClientOnlyRoute,
  AuthServerRoute: AuthServerRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SessionSessionidRoute: SessionSessionidRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
