/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowRouteImport } from './routes/_app/workflow'
import { Route as AppVerificationsRouteImport } from './routes/_app/verifications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppQuestionnariesRouteImport } from './routes/_app/questionnaries'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomizationRouteImport } from './routes/_app/customization'
import { Route as AppBlocklistRouteImport } from './routes/_app/blocklist'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationsRoute = AppVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionnariesRoute = AppQuestionnariesRouteImport.update({
  id: '/questionnaries',
  path: '/questionnaries',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizationRoute = AppCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => AppRoute,
} as any)
const AppBlocklistRoute = AppBlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/analytics': typeof AppAnalyticsRoute
  '/blocklist': typeof AppBlocklistRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/questionnaries': typeof AppQuestionnariesRoute
  '/settings': typeof AppSettingsRoute
  '/verifications': typeof AppVerificationsRoute
  '/workflow': typeof AppWorkflowRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/analytics': typeof AppAnalyticsRoute
  '/blocklist': typeof AppBlocklistRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/questionnaries': typeof AppQuestionnariesRoute
  '/settings': typeof AppSettingsRoute
  '/verifications': typeof AppVerificationsRoute
  '/workflow': typeof AppWorkflowRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/anotherPage': typeof AnotherPageRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/blocklist': typeof AppBlocklistRoute
  '/_app/customization': typeof AppCustomizationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/questionnaries': typeof AppQuestionnariesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/verifications': typeof AppVerificationsRoute
  '/_app/workflow': typeof AppWorkflowRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/analytics'
    | '/blocklist'
    | '/customization'
    | '/dashboard'
    | '/questionnaries'
    | '/settings'
    | '/verifications'
    | '/workflow'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/analytics'
    | '/blocklist'
    | '/customization'
    | '/dashboard'
    | '/questionnaries'
    | '/settings'
    | '/verifications'
    | '/workflow'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/anotherPage'
    | '/_app/analytics'
    | '/_app/blocklist'
    | '/_app/customization'
    | '/_app/dashboard'
    | '/_app/questionnaries'
    | '/_app/settings'
    | '/_app/verifications'
    | '/_app/workflow'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AnotherPageRoute: typeof AnotherPageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflow': {
      id: '/_app/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verifications': {
      id: '/_app/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof AppVerificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questionnaries': {
      id: '/_app/questionnaries'
      path: '/questionnaries'
      fullPath: '/questionnaries'
      preLoaderRoute: typeof AppQuestionnariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customization': {
      id: '/_app/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof AppCustomizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blocklist': {
      id: '/_app/blocklist'
      path: '/blocklist'
      fullPath: '/blocklist'
      preLoaderRoute: typeof AppBlocklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBlocklistRoute: typeof AppBlocklistRoute
  AppCustomizationRoute: typeof AppCustomizationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppQuestionnariesRoute: typeof AppQuestionnariesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerificationsRoute: typeof AppVerificationsRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBlocklistRoute: AppBlocklistRoute,
  AppCustomizationRoute: AppCustomizationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppQuestionnariesRoute: AppQuestionnariesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVerificationsRoute: AppVerificationsRoute,
  AppWorkflowRoute: AppWorkflowRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AnotherPageRoute: AnotherPageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
